name: Azure Webjob deploy
description: Deploy web job
inputs:
  zip-file:
    description: the zip file
    required: true
  publish-profile:
    description: 'Publish profile (*.publishsettings) file contents with Web Deploy secrets'
    required: true
  app-name:
    description: 'Name of the Azure Web App'
    required: true
  schedule-name:
    description: 'triggered or continuous'
    required: true
    default: triggered
  slot-name:
    description: 'Enter an existing Slot other than the Production slot'
    required: false
    default: 'production'
runs:
  using: node12
  main: 'index.js'
